# rustfmt.toml
edition = "2024"
hard_tabs = false
tab_spaces = 2
max_width = 100
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
fn_params_layout = "Tall"
match_block_trailing_comma = true
