import { GameData } from "../globals.slint";
import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { HandDisplay } from "../components/hand-display.slint";
import { CardView, CardData } from "../components/card-view.slint";
import { PixelButton } from "../components/pixel-button.slint";

 export component GameScreen {
    Image {
        height: root.height;
        width: root.width;
        source: @image-url("../../assets/background/backdrop.png");
    }

    VerticalBox {
        HandDisplay {
            hand: GameData.player-hand;
            label: "Your Hand";
            score: GameData.player-score;
            show-score: true;
        }

        HandDisplay {
            hand: GameData.dealer-hand;
            label: "Dealers Hand";
            score: GameData.dealer-score;
            show-score: GameData.round-over;
        }

        VerticalBox {
            HorizontalBox {
                PixelButton {
                    text: "Hit";
                    enabled: !GameData.round-over;
                    clicked => { GameData.hit(); }
                }

                PixelButton {
                    text: "Stand";
                    enabled: !GameData.round-over;
                    clicked => { GameData.stand(); }
                }
            }
        }
    }

    if GameData.round-over: Rectangle {
        background: #000000aa;
        Rectangle {
            height: 150px;
            width: 300px;

            Image {
                height: 150px;
                width: 300px;
                source: @image-url("../../assets/background/overlay.png");
            }

            VerticalBox {
                alignment: center;

                Text {
                    text: GameData.result-text;
                    font-size: 36px;
                    font-weight: 700;
                    color: white;
                    horizontal-alignment: center;
                }

                HorizontalBox {
                    Text {
                        text: "Wins: " + GameData.wins;
                        font-size: 24px;
                        color: white;
                    }

                    Text {
                        text: "Pushes: " + GameData.draws;
                        font-size: 24px;
                        color: white;
                    }

                    Text {
                        text: "Losses: " + GameData.losses;
                        font-size: 24px;
                        color: white;
                    }
                }

                HorizontalBox {
                    PixelButton {
                        text: "New Round";
                        clicked => { GameData.new_round(); }
                    }

                    PixelButton {
                        text: "Return to Menu";
                        clicked => { GameData.return_to_menu(); }
                    }
                }
            }
        }
    }
}
