import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
export struct CardData {
    image: image,
}

component CardView {
    in property <image> card-image;

    Rectangle {
        width: 54px;
        height: 76px;

        Image {
            width: 54px;
            height: 76px;
            source: card-image;
            image-rendering: pixelated;
        }
    }
}

export component AppWindow inherits Window {
    min-width: 500px;
    min-height: 500px;
    in property <[CardData]> player-hand: [];
    in property <[CardData]> dealer-hand: [];
    in property <string> result-text: "";
    in property <bool> round-over: false;
    in property <int> player-score: 0;
    in property <int> wins: 0;
    in property <int> draws: 0;
    in property <int> losses: 0;
    callback new_round();
    callback hit();
    callback stand();
    VerticalBox {
        VerticalBox {
            HorizontalBox {
                Text {
                    text: "Your Hand";
                    font-size: 24px;
                    font-weight: 700;
                    color: black;
                }

                Text {
                    text: "Hand Value: " + player-score;
                    font-size: 24px;
                    font-weight: 700;
                    color: black;
                }
            }

            HorizontalBox {
                for card in player-hand: CardView {
                    card-image: card.image;
                }
            }
        }

        VerticalBox {
            Text {
                text: "Dealers Hand";
                font-size: 24px;
                font-weight: 700;
                color: black;
            }

            HorizontalBox {
                for card in dealer-hand: CardView {
                    card-image: card.image;
                }
            }
        }

        Text {
            text: result-text;
            font-size: 20px;
            color: black;
        }

        HorizontalBox {
            Text {
                text: "Wins: " + wins;
                font-size: 20px;
                color: black;
            }

            Text {
                text: "Pushes: " + draws;
                font-size: 20px;
                color: black;
            }

            Text {
                text: "Losses: " + losses;
                font-size: 20px;
                color: black;
            }
        }

        VerticalBox {

            HorizontalBox {
                Button {
                    text: "Hit";
                    enabled: !round-over;
                    clicked => { root.hit(); }
                }

                Button {
                    text: "Stand";
                    enabled: !round-over;
                    clicked => { root.stand(); }
                }
            }

            Button {
                text: "New Round";
                enabled: round-over;
                clicked => { root.new_round(); }
            }
        }
    }
}
