import { GameScreen } from "screens/game.slint";
import { TitleScreen } from "screens/title.slint";
import "../assets/font/supersoft.ttf";

export { GameData } from "globals.slint";

enum Screen {
    title,
    game,
}

export component AppWindow inherits Window {
    width: 500px;
    height: 500px;
    default-font-family: "Pixel Font - Supersoft";
    default-font-size: 24px;
    in-out property <Screen> current-screen: title;
    callback start_game();
    callback quit();
    if current-screen == Screen.title: TitleScreen {
        start => { root.start_game(); }
        quit => { root.quit(); }
    }
    if current-screen == Screen.game: GameScreen { }
}
